name: memory_storage
description: Memory Storage Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dependencies:
  storage:
    path: ../storage

dev_dependencies:
  mocktail: 0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
