name: notify
description: notify mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.13.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #UI
  smooth_page_indicator: ^1.0.1
  font_awesome_flutter: ^10.5.0

  #l10n
  intl: ^0.18.0

  #Router
  go_router: ^10.0.0

  #Dependency Injection
  get_it: ^7.2.0

  #Bloc:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5

  #Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  #Responsive
  responsive_sizer: ^3.1.1
  responsive_builder: ^0.7.0

  #Theme
  flex_color_scheme: ^7.1.2

  #Path
  path_provider: ^2.0.11

  #Network
  dio: ^5.3.2
  alice: ^0.3.3
  pretty_dio_logger: ^1.3.1

  #Packages
  app_ui:
    path: packages/app_ui/

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Static Analyze
  flutter_lints: ^2.0.1

  #Generator
  build_runner: ^2.3.3
  build_version: ^2.1.1


flutter:
  uses-material-design: true
  generate: true