name: notify
description: notify mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.13.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #UI
  smooth_page_indicator: ^1.0.1
  font_awesome_flutter: ^10.5.0

  #Utils
  uuid: ^3.0.7

  #l10n
  intl: ^0.18.0

  #Router
  auto_route: ^7.8.3

  #Dependency Injection
  get_it: ^7.2.0

  #Bloc:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5

  #Storage
  shared_preferences: ^2.2.0

  #Path
  path_provider: ^2.0.11

  #Network
  dio: ^5.3.2
  alice: ^0.3.3
  pretty_dio_logger: ^1.3.1

  #Packages
  app_ui:
    path: packages/app_ui/

  storage:
    path: packages/storage/

  cookie_client:
    path: packages/cookie_client/


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Static Analyze
  flutter_lints: ^2.0.1

  #Generator
  auto_route_generator: ^7.3.1
  build_runner: ^2.3.3
  build_version: ^2.1.1


flutter:
  uses-material-design: true
  generate: true