name: secure_storage
description: A Key/Value Secure Storage Client
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: 8.0.0

  storage:
    path: ../storage




dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  very_good_analysis: ^5.0.0+1
