name: storage
description: A Key/Value Storage Client for Dart.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dev_dependencies:
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
