name: form_input
description: Form Input Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dependencies:
  formz: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  very_good_analysis: ^5.0.0+1
