name: cookie_client
description: The Http Client package that depends on the dio package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.4

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  alice: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
