name: persistent_storage
description: Storage that saves data in the device's persistent memory.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  very_good_analysis: ^5.0.0+1
